### ISSUE TITLE
Logo for neuron

### ISSUE THREAD

**Issue by reallinfo** [uesteibar/neuron#14]
Hello!

I am a graphic designer. I like to contribute by designing a logo for open source software. Do you want me to design a logo for neuron? I would like to hear if you have an idea.

you can see many logo design examples on my github profile.
https://github.com/reallinfo

**Comment by uesteibar** [comment]
Hi @reallinfo!

A logo would be very much welcome, feel free to open a Pull Request adding it!

Thanks ❤️

**Comment by reallinfo** [comment]
You're welcome. Okay, i designed a logo. What do you think? If you like it, i can send a pr. If there's something you want to fix, you can tell me.

![neuron](https://user-images.githubusercontent.com/36298335/40552313-feefc690-6047-11e8-9e59-1cde58172ec1.png)

**Comment by uesteibar** [comment]
Hey! I really like it, good job here 👍 🎉 

I like it either in red or in purple/dark-blue (the last one on the right). Since being a designer you have a better eye for this, I'll leave it to you to decide which one of them goes in 😃

Feel free to open a PR with the logo in any of those two colours.
Take into account that `logo: "path/to/logo",` should be added below [this line](https://github.com/uesteibar/neuron/blob/master/mix.exs#L56) in order to also show the logo in the [docs](https://hexdocs.pm/neuron/Neuron.html).

**Comment by reallinfo** [comment]
I preferred purple color. I sent a pr. I hope it is not wrong :)

Please check
https://github.com/uesteibar/neuron/pull/15
