### ISSUE TITLE
Mutations doc Examples

### ISSUE THREAD

**Issue by mbenatti** [uesteibar/neuron#17]
Hello,
First of all, thank you for the work.

I'm using this lib to debug some graphql endpoint, but I still missing documentation for mutation's, like examples and how to use input.

**Comment by uesteibar** [comment]
Hi @mbenatti!

Since the argument for `Neuron.mutation/1` is just a _string_ containing your query, you can build it the way you prefer ant then pass it in to the function.

E.g. if you wanted to pass an argument you could do:

```elixir
Neuron.mutation("""
  {
    myMutation(input: "#{ my_input }" {
      returningValue
      otherReturningValue
    }
  }
""")

```

Is that clear enough? if the documentation is not clear enough on this part, please feel free to open a pull request improving it or clarifying the points that you feel are not well explained! 😃

I hope that helps

**Comment by antonioparisi** [comment]
@uesteibar how complex arguments would look like? I'm trying to pass a Map as argument, but it gets encoded wrongly. any tip?

**Comment by uesteibar** [comment]
@antonioparisi could you provide an example on what exactly you're trying to build?
