### ISSUE TITLE
Enum graphql data type.

### ISSUE THREAD

**Issue by azzahidK** [uesteibar/neuron#49]
Hello i want to ask can i use enum data type for query in neuron, the server that i connect expecting enum for it's input. And what is the alternative if i can't do this. 

Thank you.

**Comment by uesteibar** [comment]
Hi @azzahidK!

Not sure if I understand where this question is coming from, is anything stopping you from using the enum in the query string passed to `Neuron.query`? That's a plain string so you should be able to do whatever GraphQL stuff in there.

If you could provide an example here I might be able to offer better guidance 😃

**Comment by azzahidK** [comment]
Thank you very much @uesteibar i'll do something like that but is there a way to make an atom in arguments and make it as an enum in neuron query ?

**Comment by uesteibar** [comment]
@azzahidK that currently wouldn't be possible. What happens when you declare an argument as an enum type and pass it as a graphql variable? I guess that should work as long as you declare the type of the argument properly.

Take into account that `Neuron` doesn't really interpolate your variables but sends them in the request, so the graphql server should be able to take care of differentiating between enums and regular strings, and my guess would be that it does it by checking the type of the argument.

**Comment by uesteibar** [comment]
More graphic example of what I'm proposing:

```gql
enum Action {
  UPDATE
  CREATE
}
```

```elixir
Neuron.query("""
  mutation($action: Action) {
    doSomething(action: $action)
  }
""",
%{action: "CREATE"}
)
```

My understanding is that this should work, although I didn't try it out. Could you give that a try? 😺

**Comment by azzahidK** [comment]
Thank you very much @uesteibar :D it was super helpful i'll try to implement it later. And if it is not working i'll just use normal string.
