### ISSUE TITLE
How to add timeout to Neuron

### ISSUE THREAD

**Issue by calvin-kargo** [uesteibar/neuron#63]
Hi, This is not a bug/actual issue, it just trying to help people to set HTTP timeout when using `Neuron` if needed.
HTTP timeout is handled by `Neuron.Connection` module, and default `Neuron.Connection` module used `HTTPoison` for handling HTTP connection. So to set HTTP timeout to 15 second in default `Neuron` configuration, we can pass conection options via `connection_opts`, and set `HTTPoison` `recv_timeout` to 15_000. e.g:

```
Neuron.Config.set(url: url)
Neuron.query(query, params, connection_opts: [recv_timeout: 15_000])
```

I use `Neuron` a lot, and i think it's great: easy and simple, it just a bit of shame it takes a lot of code digging just to find out how to override default timeout and maybe this would help others too.

**Comment by uesteibar** [comment]
hey @calvin-kargo! Thanks for putting this together, I think it can be really useful to folks :) however, do you think you could add it to the readme instead? I don't really want to use the issues as a place for documentation here.

Otherwise I'll do it myself but since you made the effort of putting this together I'd rather have you listed as a contributor for it ^^

**Comment by calvin-kargo** [comment]
OK, i will try to make PR for it by today, but somehow i just get stuck at installing `commitizen`, it seems like my region is having issue with NPM registry temporarily

**Comment by calvin-kargo** [comment]
https://github.com/uesteibar/neuron/pull/64

**Comment by uesteibar** [comment]
Closed as @calvin-kargo took the time to add this to the readme 🎉
