### ISSUE TITLE
Application.put_env uses global application environment

### ISSUE THREAD

**Issue by sanderhahn** [uesteibar/neuron#8]
Please note that the configuration set functions use the global application environment. This makes the configuration susceptible to race conditions when connecting to different urls and/or with different headers.

**Comment by sanderhahn** [comment]
Hmm readme didn't state, but config can be set on process. Issue might be less severe, closing again :)

**Comment by uesteibar** [comment]
Hi @sanderhahn!

this was intentional for the case where you always use the same configuration for every request.

I could deprecate the current behavior, make setting per process the default case, but still allow to set global config and make the risks clear in the readme.

I won't have access to a computer until end of year though, so I can't do it until then.

Thank you!
